url: http://ubc-subbots.github.io
baseurl: / 

# Site settings
title: UBC Subbots
email: ubc-subbots@gmail.com
description: "Presenting UBC Subbots, a collaboration between Subc and UBC Snowbots"


# Team names, titles and social links
people:
- name: Vincent Yuan
  pic: 1
  position: Founder
  social:
    - title: github
      url: http://github.com/Dulluhan
    - title: linkedin
      url: 
    - title: code
      url: #

- name: Simon Honigmann
  pic: 2
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/ubc-subbots

# Postal address (add as many lines as necessary)
address:
  - line: 2345 East Mall 
  - line: Vancouver, BC, Canada

# Build settings
markdown: kramdown
permalink: pretty
